### ISSUE TITLE
__gnu_cxx::factorial<_Tp> not defined in the --gnu_cxx namespace

### ISSUE THREAD

**Issue by developeralgo8888** [emsr/quadrature#8]
The factorial function is not defined in the __gnu_cxx namespace . i checked in jacobi.h and integrator.h and then searched the entire codebase to see where its defined but i could not find it anywhere 

No member named 'factorial' in namespace '__gnu_cxx'

is it possible to add it

**Comment by emsr** [comment]
It is possible to add. I'm pulling a small version out of another project.

**Comment by emsr** [comment]
I added factorial and several things that make this project stand-alone buildable.
At least with C++17.
If people want to go back to C++14 I can do that.

**Comment by developeralgo8888** [comment]
Thanks Rowland , have you worked with a Forex trading platform called MetaTrader 5 MQL language ( C++ Scripting variant ) from metaquotes company ?? Let me know if you have .
